/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AssessmentRouteImport } from './routes/assessment'
import { Route as AssistantRouteImport } from './routes/assistant'
import { Route as ExplorerRouteImport } from './routes/explorer'
import { Route as ObjectionRouteImport } from './routes/objection'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as RequestRouteImport } from './routes/request'
import { Route as SixRouteImport } from './routes/six'
import { Route as StandardsRouteImport } from './routes/standards'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as AdminStandardsRouteImport } from './routes/admin.standards'
import { Route as EnIndexRouteImport } from './routes/en.index'
import { Route as EnAssessmentRouteImport } from './routes/en.assessment'
import { Route as EnAssistantRouteImport } from './routes/en.assistant'
import { Route as EnObjectionRouteImport } from './routes/en.objection'
import { Route as EnPrivacyRouteImport } from './routes/en.privacy'
import { Route as EnRequestRouteImport } from './routes/en.request'
import { Route as EnSixRouteImport } from './routes/en.six'
import { Route as EnStandardsRouteImport } from './routes/en.standards'
import { Route as EnTermsRouteImport } from './routes/en.terms'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AssessmentRoute = AssessmentRouteImport.update({
  id: '/assessment',
  path: '/assessment',
  getParentRoute: () => rootRouteImport,
} as any)
const AssistantRoute = AssistantRouteImport.update({
  id: '/assistant',
  path: '/assistant',
  getParentRoute: () => rootRouteImport,
} as any)
const ExplorerRoute = ExplorerRouteImport.update({
  id: '/explorer',
  path: '/explorer',
  getParentRoute: () => rootRouteImport,
} as any)
const ObjectionRoute = ObjectionRouteImport.update({
  id: '/objection',
  path: '/objection',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const RequestRoute = RequestRouteImport.update({
  id: '/request',
  path: '/request',
  getParentRoute: () => rootRouteImport,
} as any)
const SixRoute = SixRouteImport.update({
  id: '/six',
  path: '/six',
  getParentRoute: () => rootRouteImport,
} as any)
const StandardsRoute = StandardsRouteImport.update({
  id: '/standards',
  path: '/standards',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminStandardsRoute = AdminStandardsRouteImport.update({
  id: '/admin/standards',
  path: '/admin/standards',
  getParentRoute: () => rootRouteImport,
} as any)
const EnIndexRoute = EnIndexRouteImport.update({
  id: '/en/',
  path: '/en/',
  getParentRoute: () => rootRouteImport,
} as any)
const EnAssessmentRoute = EnAssessmentRouteImport.update({
  id: '/en/assessment',
  path: '/en/assessment',
  getParentRoute: () => rootRouteImport,
} as any)
const EnAssistantRoute = EnAssistantRouteImport.update({
  id: '/en/assistant',
  path: '/en/assistant',
  getParentRoute: () => rootRouteImport,
} as any)
const EnObjectionRoute = EnObjectionRouteImport.update({
  id: '/en/objection',
  path: '/en/objection',
  getParentRoute: () => rootRouteImport,
} as any)
const EnPrivacyRoute = EnPrivacyRouteImport.update({
  id: '/en/privacy',
  path: '/en/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const EnRequestRoute = EnRequestRouteImport.update({
  id: '/en/request',
  path: '/en/request',
  getParentRoute: () => rootRouteImport,
} as any)
const EnSixRoute = EnSixRouteImport.update({
  id: '/en/six',
  path: '/en/six',
  getParentRoute: () => rootRouteImport,
} as any)
const EnStandardsRoute = EnStandardsRouteImport.update({
  id: '/en/standards',
  path: '/en/standards',
  getParentRoute: () => rootRouteImport,
} as any)
const EnTermsRoute = EnTermsRouteImport.update({
  id: '/en/terms',
  path: '/en/terms',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/assessment': typeof AssessmentRoute
  '/assistant': typeof AssistantRoute
  '/explorer': typeof ExplorerRoute
  '/objection': typeof ObjectionRoute
  '/privacy': typeof PrivacyRoute
  '/request': typeof RequestRoute
  '/six': typeof SixRoute
  '/standards': typeof StandardsRoute
  '/terms': typeof TermsRoute
  '/admin/standards': typeof AdminStandardsRoute
  '/en/assessment': typeof EnAssessmentRoute
  '/en/assistant': typeof EnAssistantRoute
  '/en/objection': typeof EnObjectionRoute
  '/en/privacy': typeof EnPrivacyRoute
  '/en/request': typeof EnRequestRoute
  '/en/six': typeof EnSixRoute
  '/en/standards': typeof EnStandardsRoute
  '/en/terms': typeof EnTermsRoute
  '/en/': typeof EnIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/assessment': typeof AssessmentRoute
  '/assistant': typeof AssistantRoute
  '/explorer': typeof ExplorerRoute
  '/objection': typeof ObjectionRoute
  '/privacy': typeof PrivacyRoute
  '/request': typeof RequestRoute
  '/six': typeof SixRoute
  '/standards': typeof StandardsRoute
  '/terms': typeof TermsRoute
  '/admin/standards': typeof AdminStandardsRoute
  '/en/assessment': typeof EnAssessmentRoute
  '/en/assistant': typeof EnAssistantRoute
  '/en/objection': typeof EnObjectionRoute
  '/en/privacy': typeof EnPrivacyRoute
  '/en/request': typeof EnRequestRoute
  '/en/six': typeof EnSixRoute
  '/en/standards': typeof EnStandardsRoute
  '/en/terms': typeof EnTermsRoute
  '/en': typeof EnIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/assessment': typeof AssessmentRoute
  '/assistant': typeof AssistantRoute
  '/explorer': typeof ExplorerRoute
  '/objection': typeof ObjectionRoute
  '/privacy': typeof PrivacyRoute
  '/request': typeof RequestRoute
  '/six': typeof SixRoute
  '/standards': typeof StandardsRoute
  '/terms': typeof TermsRoute
  '/admin/standards': typeof AdminStandardsRoute
  '/en/assessment': typeof EnAssessmentRoute
  '/en/assistant': typeof EnAssistantRoute
  '/en/objection': typeof EnObjectionRoute
  '/en/privacy': typeof EnPrivacyRoute
  '/en/request': typeof EnRequestRoute
  '/en/six': typeof EnSixRoute
  '/en/standards': typeof EnStandardsRoute
  '/en/terms': typeof EnTermsRoute
  '/en/': typeof EnIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/assessment'
    | '/assistant'
    | '/explorer'
    | '/objection'
    | '/privacy'
    | '/request'
    | '/six'
    | '/standards'
    | '/terms'
    | '/admin/standards'
    | '/en/assessment'
    | '/en/assistant'
    | '/en/objection'
    | '/en/privacy'
    | '/en/request'
    | '/en/six'
    | '/en/standards'
    | '/en/terms'
    | '/en/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/assessment'
    | '/assistant'
    | '/explorer'
    | '/objection'
    | '/privacy'
    | '/request'
    | '/six'
    | '/standards'
    | '/terms'
    | '/admin/standards'
    | '/en/assessment'
    | '/en/assistant'
    | '/en/objection'
    | '/en/privacy'
    | '/en/request'
    | '/en/six'
    | '/en/standards'
    | '/en/terms'
    | '/en'
  id:
    | '__root__'
    | '/'
    | '/assessment'
    | '/assistant'
    | '/explorer'
    | '/objection'
    | '/privacy'
    | '/request'
    | '/six'
    | '/standards'
    | '/terms'
    | '/admin/standards'
    | '/en/assessment'
    | '/en/assistant'
    | '/en/objection'
    | '/en/privacy'
    | '/en/request'
    | '/en/six'
    | '/en/standards'
    | '/en/terms'
    | '/en/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AssessmentRoute: typeof AssessmentRoute
  AssistantRoute: typeof AssistantRoute
  ExplorerRoute: typeof ExplorerRoute
  ObjectionRoute: typeof ObjectionRoute
  PrivacyRoute: typeof PrivacyRoute
  RequestRoute: typeof RequestRoute
  SixRoute: typeof SixRoute
  StandardsRoute: typeof StandardsRoute
  TermsRoute: typeof TermsRoute
  AdminStandardsRoute: typeof AdminStandardsRoute
  EnAssessmentRoute: typeof EnAssessmentRoute
  EnAssistantRoute: typeof EnAssistantRoute
  EnObjectionRoute: typeof EnObjectionRoute
  EnPrivacyRoute: typeof EnPrivacyRoute
  EnRequestRoute: typeof EnRequestRoute
  EnSixRoute: typeof EnSixRoute
  EnStandardsRoute: typeof EnStandardsRoute
  EnTermsRoute: typeof EnTermsRoute
  EnIndexRoute: typeof EnIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assessment': {
      id: '/assessment'
      path: '/assessment'
      fullPath: '/assessment'
      preLoaderRoute: typeof AssessmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assistant': {
      id: '/assistant'
      path: '/assistant'
      fullPath: '/assistant'
      preLoaderRoute: typeof AssistantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explorer': {
      id: '/explorer'
      path: '/explorer'
      fullPath: '/explorer'
      preLoaderRoute: typeof ExplorerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/objection': {
      id: '/objection'
      path: '/objection'
      fullPath: '/objection'
      preLoaderRoute: typeof ObjectionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/request': {
      id: '/request'
      path: '/request'
      fullPath: '/request'
      preLoaderRoute: typeof RequestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/six': {
      id: '/six'
      path: '/six'
      fullPath: '/six'
      preLoaderRoute: typeof SixRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/standards': {
      id: '/standards'
      path: '/standards'
      fullPath: '/standards'
      preLoaderRoute: typeof StandardsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/standards': {
      id: '/admin/standards'
      path: '/admin/standards'
      fullPath: '/admin/standards'
      preLoaderRoute: typeof AdminStandardsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/en/': {
      id: '/en/'
      path: '/en'
      fullPath: '/en/'
      preLoaderRoute: typeof EnIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/en/assessment': {
      id: '/en/assessment'
      path: '/en/assessment'
      fullPath: '/en/assessment'
      preLoaderRoute: typeof EnAssessmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/en/assistant': {
      id: '/en/assistant'
      path: '/en/assistant'
      fullPath: '/en/assistant'
      preLoaderRoute: typeof EnAssistantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/en/objection': {
      id: '/en/objection'
      path: '/en/objection'
      fullPath: '/en/objection'
      preLoaderRoute: typeof EnObjectionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/en/privacy': {
      id: '/en/privacy'
      path: '/en/privacy'
      fullPath: '/en/privacy'
      preLoaderRoute: typeof EnPrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/en/request': {
      id: '/en/request'
      path: '/en/request'
      fullPath: '/en/request'
      preLoaderRoute: typeof EnRequestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/en/six': {
      id: '/en/six'
      path: '/en/six'
      fullPath: '/en/six'
      preLoaderRoute: typeof EnSixRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/en/standards': {
      id: '/en/standards'
      path: '/en/standards'
      fullPath: '/en/standards'
      preLoaderRoute: typeof EnStandardsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/en/terms': {
      id: '/en/terms'
      path: '/en/terms'
      fullPath: '/en/terms'
      preLoaderRoute: typeof EnTermsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AssessmentRoute: AssessmentRoute,
  AssistantRoute: AssistantRoute,
  ExplorerRoute: ExplorerRoute,
  ObjectionRoute: ObjectionRoute,
  PrivacyRoute: PrivacyRoute,
  RequestRoute: RequestRoute,
  SixRoute: SixRoute,
  StandardsRoute: StandardsRoute,
  TermsRoute: TermsRoute,
  AdminStandardsRoute: AdminStandardsRoute,
  EnAssessmentRoute: EnAssessmentRoute,
  EnAssistantRoute: EnAssistantRoute,
  EnObjectionRoute: EnObjectionRoute,
  EnPrivacyRoute: EnPrivacyRoute,
  EnRequestRoute: EnRequestRoute,
  EnSixRoute: EnSixRoute,
  EnStandardsRoute: EnStandardsRoute,
  EnTermsRoute: EnTermsRoute,
  EnIndexRoute: EnIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
