/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AssessmentRouteImport } from './routes/assessment'
import { Route as AssistantRouteImport } from './routes/assistant'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ClassificationStandardsRouteImport } from './routes/classification-standards'
import { Route as EnRouteImport } from './routes/en'
import { Route as ExplorerRouteImport } from './routes/explorer'
import { Route as MapRouteImport } from './routes/map'
import { Route as ObjectionRouteImport } from './routes/objection'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as RequestRouteImport } from './routes/request'
import { Route as SixRouteImport } from './routes/six'
import { Route as StandardsRouteImport } from './routes/standards'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as WaqfRouteImport } from './routes/waqf'
import { Route as AuthenticatedReviewRouteImport } from './routes/_authenticated/review'
import { Route as AdminStandardsRouteImport } from './routes/admin.standards'
import { Route as EnAssessmentRouteImport } from './routes/en.assessment'
import { Route as EnAssistantRouteImport } from './routes/en.assistant'
import { Route as EnClassificationStandardsRouteImport } from './routes/en.classification-standards'
import { Route as EnMapRouteImport } from './routes/en.map'
import { Route as EnObjectionRouteImport } from './routes/en.objection'
import { Route as EnPrivacyRouteImport } from './routes/en.privacy'
import { Route as EnRequestRouteImport } from './routes/en.request'
import { Route as EnSixRouteImport } from './routes/en.six'
import { Route as EnStandardsRouteImport } from './routes/en.standards'
import { Route as EnTermsRouteImport } from './routes/en.terms'
import { Route as EnWaqfRouteImport } from './routes/en.waqf'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AssessmentRoute = AssessmentRouteImport.update({
  id: '/assessment',
  path: '/assessment',
  getParentRoute: () => rootRouteImport,
} as any)
const AssistantRoute = AssistantRouteImport.update({
  id: '/assistant',
  path: '/assistant',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ClassificationStandardsRoute = ClassificationStandardsRouteImport.update({
  id: '/classification-standards',
  path: '/classification-standards',
  getParentRoute: () => rootRouteImport,
} as any)
const EnRoute = EnRouteImport.update({
  id: '/en',
  path: '/en',
  getParentRoute: () => rootRouteImport,
} as any)
const ExplorerRoute = ExplorerRouteImport.update({
  id: '/explorer',
  path: '/explorer',
  getParentRoute: () => rootRouteImport,
} as any)
const MapRoute = MapRouteImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => rootRouteImport,
} as any)
const ObjectionRoute = ObjectionRouteImport.update({
  id: '/objection',
  path: '/objection',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const RequestRoute = RequestRouteImport.update({
  id: '/request',
  path: '/request',
  getParentRoute: () => rootRouteImport,
} as any)
const SixRoute = SixRouteImport.update({
  id: '/six',
  path: '/six',
  getParentRoute: () => rootRouteImport,
} as any)
const StandardsRoute = StandardsRouteImport.update({
  id: '/standards',
  path: '/standards',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const WaqfRoute = WaqfRouteImport.update({
  id: '/waqf',
  path: '/waqf',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedReviewRoute = AuthenticatedReviewRouteImport.update({
  id: '/review',
  path: '/review',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AdminStandardsRoute = AdminStandardsRouteImport.update({
  id: '/admin/standards',
  path: '/admin/standards',
  getParentRoute: () => rootRouteImport,
} as any)
const EnAssessmentRoute = EnAssessmentRouteImport.update({
  id: '/assessment',
  path: '/assessment',
  getParentRoute: () => EnRoute,
} as any)
const EnAssistantRoute = EnAssistantRouteImport.update({
  id: '/assistant',
  path: '/assistant',
  getParentRoute: () => EnRoute,
} as any)
const EnClassificationStandardsRoute =
  EnClassificationStandardsRouteImport.update({
    id: '/classification-standards',
    path: '/classification-standards',
    getParentRoute: () => EnRoute,
  } as any)
const EnMapRoute = EnMapRouteImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => EnRoute,
} as any)
const EnObjectionRoute = EnObjectionRouteImport.update({
  id: '/objection',
  path: '/objection',
  getParentRoute: () => EnRoute,
} as any)
const EnPrivacyRoute = EnPrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => EnRoute,
} as any)
const EnRequestRoute = EnRequestRouteImport.update({
  id: '/request',
  path: '/request',
  getParentRoute: () => EnRoute,
} as any)
const EnSixRoute = EnSixRouteImport.update({
  id: '/six',
  path: '/six',
  getParentRoute: () => EnRoute,
} as any)
const EnStandardsRoute = EnStandardsRouteImport.update({
  id: '/standards',
  path: '/standards',
  getParentRoute: () => EnRoute,
} as any)
const EnTermsRoute = EnTermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => EnRoute,
} as any)
const EnWaqfRoute = EnWaqfRouteImport.update({
  id: '/waqf',
  path: '/waqf',
  getParentRoute: () => EnRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/assessment': typeof AssessmentRoute
  '/assistant': typeof AssistantRoute
  '/auth': typeof AuthRoute
  '/classification-standards': typeof ClassificationStandardsRoute
  '/en': typeof EnRouteWithChildren
  '/explorer': typeof ExplorerRoute
  '/map': typeof MapRoute
  '/objection': typeof ObjectionRoute
  '/privacy': typeof PrivacyRoute
  '/request': typeof RequestRoute
  '/six': typeof SixRoute
  '/standards': typeof StandardsRoute
  '/terms': typeof TermsRoute
  '/waqf': typeof WaqfRoute
  '/review': typeof AuthenticatedReviewRoute
  '/admin/standards': typeof AdminStandardsRoute
  '/en/assessment': typeof EnAssessmentRoute
  '/en/assistant': typeof EnAssistantRoute
  '/en/classification-standards': typeof EnClassificationStandardsRoute
  '/en/map': typeof EnMapRoute
  '/en/objection': typeof EnObjectionRoute
  '/en/privacy': typeof EnPrivacyRoute
  '/en/request': typeof EnRequestRoute
  '/en/six': typeof EnSixRoute
  '/en/standards': typeof EnStandardsRoute
  '/en/terms': typeof EnTermsRoute
  '/en/waqf': typeof EnWaqfRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/assessment': typeof AssessmentRoute
  '/assistant': typeof AssistantRoute
  '/auth': typeof AuthRoute
  '/classification-standards': typeof ClassificationStandardsRoute
  '/en': typeof EnRouteWithChildren
  '/explorer': typeof ExplorerRoute
  '/map': typeof MapRoute
  '/objection': typeof ObjectionRoute
  '/privacy': typeof PrivacyRoute
  '/request': typeof RequestRoute
  '/six': typeof SixRoute
  '/standards': typeof StandardsRoute
  '/terms': typeof TermsRoute
  '/waqf': typeof WaqfRoute
  '/review': typeof AuthenticatedReviewRoute
  '/admin/standards': typeof AdminStandardsRoute
  '/en/assessment': typeof EnAssessmentRoute
  '/en/assistant': typeof EnAssistantRoute
  '/en/classification-standards': typeof EnClassificationStandardsRoute
  '/en/map': typeof EnMapRoute
  '/en/objection': typeof EnObjectionRoute
  '/en/privacy': typeof EnPrivacyRoute
  '/en/request': typeof EnRequestRoute
  '/en/six': typeof EnSixRoute
  '/en/standards': typeof EnStandardsRoute
  '/en/terms': typeof EnTermsRoute
  '/en/waqf': typeof EnWaqfRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/assessment': typeof AssessmentRoute
  '/assistant': typeof AssistantRoute
  '/auth': typeof AuthRoute
  '/classification-standards': typeof ClassificationStandardsRoute
  '/en': typeof EnRouteWithChildren
  '/explorer': typeof ExplorerRoute
  '/map': typeof MapRoute
  '/objection': typeof ObjectionRoute
  '/privacy': typeof PrivacyRoute
  '/request': typeof RequestRoute
  '/six': typeof SixRoute
  '/standards': typeof StandardsRoute
  '/terms': typeof TermsRoute
  '/waqf': typeof WaqfRoute
  '/_authenticated/review': typeof AuthenticatedReviewRoute
  '/admin/standards': typeof AdminStandardsRoute
  '/en/assessment': typeof EnAssessmentRoute
  '/en/assistant': typeof EnAssistantRoute
  '/en/classification-standards': typeof EnClassificationStandardsRoute
  '/en/map': typeof EnMapRoute
  '/en/objection': typeof EnObjectionRoute
  '/en/privacy': typeof EnPrivacyRoute
  '/en/request': typeof EnRequestRoute
  '/en/six': typeof EnSixRoute
  '/en/standards': typeof EnStandardsRoute
  '/en/terms': typeof EnTermsRoute
  '/en/waqf': typeof EnWaqfRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/assessment'
    | '/assistant'
    | '/auth'
    | '/classification-standards'
    | '/en'
    | '/explorer'
    | '/map'
    | '/objection'
    | '/privacy'
    | '/request'
    | '/six'
    | '/standards'
    | '/terms'
    | '/waqf'
    | '/review'
    | '/admin/standards'
    | '/en/assessment'
    | '/en/assistant'
    | '/en/classification-standards'
    | '/en/map'
    | '/en/objection'
    | '/en/privacy'
    | '/en/request'
    | '/en/six'
    | '/en/standards'
    | '/en/terms'
    | '/en/waqf'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/assessment'
    | '/assistant'
    | '/auth'
    | '/classification-standards'
    | '/en'
    | '/explorer'
    | '/map'
    | '/objection'
    | '/privacy'
    | '/request'
    | '/six'
    | '/standards'
    | '/terms'
    | '/waqf'
    | '/review'
    | '/admin/standards'
    | '/en/assessment'
    | '/en/assistant'
    | '/en/classification-standards'
    | '/en/map'
    | '/en/objection'
    | '/en/privacy'
    | '/en/request'
    | '/en/six'
    | '/en/standards'
    | '/en/terms'
    | '/en/waqf'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/assessment'
    | '/assistant'
    | '/auth'
    | '/classification-standards'
    | '/en'
    | '/explorer'
    | '/map'
    | '/objection'
    | '/privacy'
    | '/request'
    | '/six'
    | '/standards'
    | '/terms'
    | '/waqf'
    | '/_authenticated/review'
    | '/admin/standards'
    | '/en/assessment'
    | '/en/assistant'
    | '/en/classification-standards'
    | '/en/map'
    | '/en/objection'
    | '/en/privacy'
    | '/en/request'
    | '/en/six'
    | '/en/standards'
    | '/en/terms'
    | '/en/waqf'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AssessmentRoute: typeof AssessmentRoute
  AssistantRoute: typeof AssistantRoute
  AuthRoute: typeof AuthRoute
  ClassificationStandardsRoute: typeof ClassificationStandardsRoute
  EnRoute: typeof EnRouteWithChildren
  ExplorerRoute: typeof ExplorerRoute
  MapRoute: typeof MapRoute
  ObjectionRoute: typeof ObjectionRoute
  PrivacyRoute: typeof PrivacyRoute
  RequestRoute: typeof RequestRoute
  SixRoute: typeof SixRoute
  StandardsRoute: typeof StandardsRoute
  TermsRoute: typeof TermsRoute
  WaqfRoute: typeof WaqfRoute
  AdminStandardsRoute: typeof AdminStandardsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assessment': {
      id: '/assessment'
      path: '/assessment'
      fullPath: '/assessment'
      preLoaderRoute: typeof AssessmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assistant': {
      id: '/assistant'
      path: '/assistant'
      fullPath: '/assistant'
      preLoaderRoute: typeof AssistantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/classification-standards': {
      id: '/classification-standards'
      path: '/classification-standards'
      fullPath: '/classification-standards'
      preLoaderRoute: typeof ClassificationStandardsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/en': {
      id: '/en'
      path: '/en'
      fullPath: '/en'
      preLoaderRoute: typeof EnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explorer': {
      id: '/explorer'
      path: '/explorer'
      fullPath: '/explorer'
      preLoaderRoute: typeof ExplorerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/map': {
      id: '/map'
      path: '/map'
      fullPath: '/map'
      preLoaderRoute: typeof MapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/objection': {
      id: '/objection'
      path: '/objection'
      fullPath: '/objection'
      preLoaderRoute: typeof ObjectionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/request': {
      id: '/request'
      path: '/request'
      fullPath: '/request'
      preLoaderRoute: typeof RequestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/six': {
      id: '/six'
      path: '/six'
      fullPath: '/six'
      preLoaderRoute: typeof SixRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/standards': {
      id: '/standards'
      path: '/standards'
      fullPath: '/standards'
      preLoaderRoute: typeof StandardsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/waqf': {
      id: '/waqf'
      path: '/waqf'
      fullPath: '/waqf'
      preLoaderRoute: typeof WaqfRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/review': {
      id: '/_authenticated/review'
      path: '/review'
      fullPath: '/review'
      preLoaderRoute: typeof AuthenticatedReviewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/admin/standards': {
      id: '/admin/standards'
      path: '/admin/standards'
      fullPath: '/admin/standards'
      preLoaderRoute: typeof AdminStandardsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/en/assessment': {
      id: '/en/assessment'
      path: '/assessment'
      fullPath: '/en/assessment'
      preLoaderRoute: typeof EnAssessmentRouteImport
      parentRoute: typeof EnRoute
    }
    '/en/assistant': {
      id: '/en/assistant'
      path: '/assistant'
      fullPath: '/en/assistant'
      preLoaderRoute: typeof EnAssistantRouteImport
      parentRoute: typeof EnRoute
    }
    '/en/classification-standards': {
      id: '/en/classification-standards'
      path: '/classification-standards'
      fullPath: '/en/classification-standards'
      preLoaderRoute: typeof EnClassificationStandardsRouteImport
      parentRoute: typeof EnRoute
    }
    '/en/map': {
      id: '/en/map'
      path: '/map'
      fullPath: '/en/map'
      preLoaderRoute: typeof EnMapRouteImport
      parentRoute: typeof EnRoute
    }
    '/en/objection': {
      id: '/en/objection'
      path: '/objection'
      fullPath: '/en/objection'
      preLoaderRoute: typeof EnObjectionRouteImport
      parentRoute: typeof EnRoute
    }
    '/en/privacy': {
      id: '/en/privacy'
      path: '/privacy'
      fullPath: '/en/privacy'
      preLoaderRoute: typeof EnPrivacyRouteImport
      parentRoute: typeof EnRoute
    }
    '/en/request': {
      id: '/en/request'
      path: '/request'
      fullPath: '/en/request'
      preLoaderRoute: typeof EnRequestRouteImport
      parentRoute: typeof EnRoute
    }
    '/en/six': {
      id: '/en/six'
      path: '/six'
      fullPath: '/en/six'
      preLoaderRoute: typeof EnSixRouteImport
      parentRoute: typeof EnRoute
    }
    '/en/standards': {
      id: '/en/standards'
      path: '/standards'
      fullPath: '/en/standards'
      preLoaderRoute: typeof EnStandardsRouteImport
      parentRoute: typeof EnRoute
    }
    '/en/terms': {
      id: '/en/terms'
      path: '/terms'
      fullPath: '/en/terms'
      preLoaderRoute: typeof EnTermsRouteImport
      parentRoute: typeof EnRoute
    }
    '/en/waqf': {
      id: '/en/waqf'
      path: '/waqf'
      fullPath: '/en/waqf'
      preLoaderRoute: typeof EnWaqfRouteImport
      parentRoute: typeof EnRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedReviewRoute: typeof AuthenticatedReviewRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedReviewRoute: AuthenticatedReviewRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface EnRouteChildren {
  EnAssessmentRoute: typeof EnAssessmentRoute
  EnAssistantRoute: typeof EnAssistantRoute
  EnClassificationStandardsRoute: typeof EnClassificationStandardsRoute
  EnMapRoute: typeof EnMapRoute
  EnObjectionRoute: typeof EnObjectionRoute
  EnPrivacyRoute: typeof EnPrivacyRoute
  EnRequestRoute: typeof EnRequestRoute
  EnSixRoute: typeof EnSixRoute
  EnStandardsRoute: typeof EnStandardsRoute
  EnTermsRoute: typeof EnTermsRoute
  EnWaqfRoute: typeof EnWaqfRoute
}

const EnRouteChildren: EnRouteChildren = {
  EnAssessmentRoute: EnAssessmentRoute,
  EnAssistantRoute: EnAssistantRoute,
  EnClassificationStandardsRoute: EnClassificationStandardsRoute,
  EnMapRoute: EnMapRoute,
  EnObjectionRoute: EnObjectionRoute,
  EnPrivacyRoute: EnPrivacyRoute,
  EnRequestRoute: EnRequestRoute,
  EnSixRoute: EnSixRoute,
  EnStandardsRoute: EnStandardsRoute,
  EnTermsRoute: EnTermsRoute,
  EnWaqfRoute: EnWaqfRoute,
}

const EnRouteWithChildren = EnRoute._addFileChildren(EnRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AssessmentRoute: AssessmentRoute,
  AssistantRoute: AssistantRoute,
  AuthRoute: AuthRoute,
  ClassificationStandardsRoute: ClassificationStandardsRoute,
  EnRoute: EnRouteWithChildren,
  ExplorerRoute: ExplorerRoute,
  MapRoute: MapRoute,
  ObjectionRoute: ObjectionRoute,
  PrivacyRoute: PrivacyRoute,
  RequestRoute: RequestRoute,
  SixRoute: SixRoute,
  StandardsRoute: StandardsRoute,
  TermsRoute: TermsRoute,
  WaqfRoute: WaqfRoute,
  AdminStandardsRoute: AdminStandardsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
